#!/bin/bash

brightness=$(brightnessctl get)
max=$(brightnessctl max)
percent=$((brightness * 100 / max))

notify-send "🔆 Brilho" "$percent%" \
-h int:value:$percent \
-h string:x-canonical-private-synchronous:brightness
