#!/bin/bash
# ~/.local/bin/volume-notify.sh
VOL=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{printf "%d", $2 * 100}')
notify-send -a "volume" -h int:value:$VOL -t 2500 \
  -h string:x-canonical-private-synchronous:volume \
  "🔊 Volume" "$VOL%"
